#!/usr/bin/env node
/**
 * Zero-dependency mini bundler.
 *
 * Wraps the CommonJS engine/word/powerpoint modules into a single browser
 * bundle (dist/bundle.js) with a tiny path-aware require shim. Keeps the
 * source modules CommonJS so the same code runs under `node --test`.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "dist", "bundle.js");

// Logical module key (how modules reference each other, e.g. "../engine/model.js")
// -> absolute file path. Keys mirror the directory layout under src/.
const MODULES = {
  "engine/model.js": path.join(ROOT, "src", "engine", "model.js"),
  "engine/evaluators.js": path.join(ROOT, "src", "engine", "evaluators.js"),
  "engine/engine.js": path.join(ROOT, "src", "engine", "engine.js"),
  "word/extractor.js": path.join(ROOT, "src", "word", "extractor.js"),
  "word/fixer.js": path.join(ROOT, "src", "word", "fixer.js"),
  "powerpoint/extractor.js": path.join(ROOT, "src", "powerpoint", "extractor.js"),
  "powerpoint/fixer.js": path.join(ROOT, "src", "powerpoint", "fixer.js"),
};

const banner = `/* DFSWM Compliance Plugin - browser bundle (generated by scripts/build-browser.js) */
(function () {
  "use strict";
  var modules = {};

  function def(id, fn) { modules[id] = { fn: fn, exports: {}, loaded: false }; }

  // Resolve a require specifier (e.g. "./model.js", "../engine/model.js")
  // against the caller's module key (e.g. "word/extractor.js").
  function resolve(caller, spec) {
    var id = String(spec);
    if (id.charAt(0) !== ".") return id; // bare identifier
    var dir = caller.indexOf("/") === -1 ? "" : caller.slice(0, caller.lastIndexOf("/"));
    var parts = dir ? dir.split("/") : [];
    id.split("/").forEach(function (seg) {
      if (seg === "." || seg === "") return;
      if (seg === "..") parts.pop();
      else parts.push(seg);
    });
    return parts.join("/");
  }

  function makeRequire(caller) {
    return function (id) {
      var key = resolve(caller, id);
      var m = modules[key];
      if (!m) throw new Error("Module not found: " + id + " (key: " + key + ")");
      if (!m.loaded) {
        m.loaded = true;
        m.fn(m, m.exports, makeRequire(key));
      }
      return m.exports;
    };
  }
`;

const footer = `
  var require = makeRequire("");
  window.DFSWM = {
    runCompliance: require("engine/engine.js").runCompliance,
    groupBySeverity: require("engine/engine.js").groupBySeverity,
    normalizeModel: require("engine/model.js").normalizeModel,
    extractDocumentModel: require("word/extractor.js").extractDocumentModel,
    applyFix: require("word/fixer.js").applyFix,
    extractPresentationModel: require("powerpoint/extractor.js").extractPresentationModel,
    applyPptFix: require("powerpoint/fixer.js").applyFix
  };
})();
`;

let body = banner;
for (const [key, file] of Object.entries(MODULES)) {
  const src = fs.readFileSync(file, "utf8");
  body += `\ndef(${JSON.stringify(key)}, function (module, exports, require) {\n${src}\n});\n`;
}
body += footer;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(`Built ${path.relative(ROOT, OUT)} (${body.length} bytes, ${Object.keys(MODULES).length} modules)`);
