#!/usr/bin/env node
/**
 * Zero-dependency mini bundler.
 *
 * Wraps the CommonJS engine/word modules into a single browser bundle
 * (dist/bundle.js) with a tiny require shim. Keeps the source modules
 * CommonJS so the same code runs under `node --test`.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "dist", "bundle.js");

// module key (as referenced in require(), e.g. './model.js') -> file path
const MODULES = {
  "model.js": path.join(ROOT, "src", "engine", "model.js"),
  "evaluators.js": path.join(ROOT, "src", "engine", "evaluators.js"),
  "engine.js": path.join(ROOT, "src", "engine", "engine.js"),
  "extractor.js": path.join(ROOT, "src", "word", "extractor.js"),
  "fixer.js": path.join(ROOT, "src", "word", "fixer.js"),
};

const banner = `/* DFSWM Compliance Plugin - browser bundle (generated by scripts/build-browser.js) */
(function () {
  "use strict";
  var modules = {};

  function def(id, fn) { modules[id] = { fn: fn, exports: {}, loaded: false }; }

  // Keys are registered WITH the .js extension (e.g. "model.js"); require()
  // calls use "./model.js" — strip only the relative prefix.
  function require(id) {
    var key = String(id).replace(/^\\.\\//, "");
    var m = modules[key];
    if (!m) throw new Error("Module not found: " + id);
    if (!m.loaded) {
      m.loaded = true;
      m.fn(m, m.exports, function (dep) { return require(dep); });
    }
    return m.exports;
  }
`;

const footer = `
  window.DFSWM = {
    runCompliance: require("engine.js").runCompliance,
    groupBySeverity: require("engine.js").groupBySeverity,
    normalizeModel: require("model.js").normalizeModel,
    extractDocumentModel: require("extractor.js").extractDocumentModel,
    applyFix: require("fixer.js").applyFix
  };
})();
`;

let body = banner;
for (const [key, file] of Object.entries(MODULES)) {
  const src = fs.readFileSync(file, "utf8");
  body += `\ndef(${JSON.stringify(key)}, function (module, exports, require) {\n${src}\n});\n`;
}
body += footer;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(`Built ${path.relative(ROOT, OUT)} (${body.length} bytes, ${Object.keys(MODULES).length} modules)`);
